name: SerManos
description: TPE 73.21 - Desarrollo de Aplicaciones Móviles Multiplataforma Segundo Cuatrimestre 2023.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.13.0
  firebase_crashlytics: ^3.4.4
  firebase_analytics: ^10.6.4
  firebase_storage: ^11.5.0
  mask_text_input_formatter: ^2.5.0
  image_picker: ^1.0.4
  logger: ^2.0.2+1
  hooks_riverpod: ^2.4.5
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.3.0
  go_router: ^12.1.1
  dio: ^5.3.3
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  fake_cloud_firestore: ^2.4.3
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  geolocator: ^10.1.0
  flutter_markdown: ^0.6.18+2
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.3.5
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lib/.env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
