// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: "AIzaSyBGOayX-WQxDUeRat4NRnaoiGP6lGKBUw0",
    appId: "1:666241362205:android:5cd99cac2d2fb9d9c859f4",
    messagingSenderId: "666241362205",
    projectId: "sermanos-91896",
    storageBucket: "sermanos-91896.appspot.com",
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: "AIzaSyBRC-T9Oy7Mq8tdGETx3VuAVfCmoaYhaTs",
    appId: "1:666241362205:ios:b8d435e304747628c859f4",
    iosBundleId: "com.example.fluttertest",
    messagingSenderId: "666241362205",
    projectId: "sermanos-91896",
    storageBucket: "sermanos-91896.appspot.com",
  );
}
